// let dept = 'programming';
// let Department='programming';
    
//     typeof('programming')
//     console.log(typeof(Department))
    
    
//         let grade= 'A1';
//         console.log(grade)

//         let age= 20;
//         age= 40;
//         typeof(20)
//         console.log(age);

//         let Firstname= 'koo';
//         let Lastname= 'akata';
//         console.log(Firstname)

//         let sum= 200 + 300;
//         let multiply= 400 * 2;
//         let divide= 400/2;
//         console.log(divide)
//         console.log(multiply)
    
//         let y= 200;
//         y *= 50;
//         y += 200;
//         console.log(y)
       
// let age = 50; 
// if 
//        (age < 18)
//       {console.log 
//     ( "you  are under age , so you are not eligible" ); }
// else if
//        ( age >= 18 && age <= 50 ) 
//       { console.log ( "you are eligible" ) }
// else
//       { console.log (" you are too old, so you are not eligible" );}

// let day = 3;
// switch(day) {
// case 1: 
//      console.log ("MONDAY")
//      break;
// case 2: 
//      console.log ("TUESDAY")
//     break;

// }

// function addAndlog(a, b){
// console.log(a + b);
//  }

// addAndlog(10 , 5);


// const addition =  addAndlog(a ,b) =>
//  return result = a + b;

// console.log (addAndlog (10 , 5);

// let message = "HELLO"
// const greetings =()=>
    
    const AREA = calculate(H , W) =>
    return results= H * W;
   
    console.log (calculateArea (5,5));

    